apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: default
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-container
          image: scoma/spring-ms-tp1_eureka:v2
          env:
            - name: server.port
              value: '8761'
            - name: eureka.client.fetch-registry
              value: 'false'
            - name: eureka.client.register-with-eureka
              value: 'false'
          ports:
            - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: default
  labels:
    run: eureka-service
spec:
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  type: LoadBalancer
  selector:
    app: eureka
